### ISSUE TITLE
Doesnt seem to be working on https urls

### ISSUE THREAD

**Issue by peyloride** [mimnix/FlareProxy#4]
Hey!

First of all thanks for your work! It seems very reasonable and I'm glad someone else that thought the same thing; using changedetection with flaresolverr to evade some CF captchas.

Problem is it seems this proxy only works with HTTP requests. Here is how I run:

- I have proxmox running
- One of the nodes running flaresolverr separately, running on 192.168.1.195:8191 (confirmed it's working as expected)
- Another VM node runs all docker containers (running on 192.168.1.132)
- Here is how I run FlareProxy:
```
version: "3.8"
services:
  flareproxy:
    image: ghcr.io/mimnix/flareproxy:v1.0.0
    container_name: flareproxy
    environment:
      - FLARESOLVERR_URL=http://192.168.1.195:8191/v1
      - TZ=Europe/Istanbul
    ports:
      - 8080:8080
    restart: always
networks: {}
```

- Then in the changedetection, I've set an extra proxy as
```
http://192.168.1.132:8080 (132 is where the docker VM lives)
```

When I test on http website, it worked. But when I tried on some https website, it gives this error:

```
Exception: Page.goto: net::ERR_TUNNEL_CONNECTION_FAILED at https://www.redacted.com Call log: - navigating to "https://www.redacted.com/", waiting until "load" 
```

Thanks!
